http {
    server {
        listen 0.0.0.0:8080;
        error_page 404 =200 /index.html;
        location / {
            root docs/html/;
            index index.html;
            allow_methods GET HEAD POST;
        }

        location /img {
            root docs/img/;
            index icon.jpeg;
        }

        location /upload {
            upload_store docs/uploads;
            client_max_body_size 10k;
        }

        location /404 {
            root docs/error;
        }

        location /delete {
            root docs;
            allow_methods GET POST HEAD DELETE;
        }

        location /autoindex {
            autoindex on;
            root docs;
        }

        location /cgi-bin/ {
            root ./;
            cgi_extension .py;
            cgi_path /usr/bin/python3;
            allow_methods GET POST HEAD;
        }
    }
}
