http {
    server {
        listen 0.0.0.0:8080;
        location / {
            root docs/html/;
            index index.html;
            allow_methods GET HEAD POST;
        }

        location /img {
            root docs;
            index icon.jpeg;
        }

        location /upload {
            upload_store docs/uploads;
            client_max_body_size 10k;
        }

        location /error {
            root docs;
            index index.html;
            error_page 403 /403.html;
            error_page 500 =200 /index.html;
        }

        location /403 {
            root docs/error;
        }

        location /delete {
            root docs;
            allow_methods GET POST HEAD DELETE;
        }

        location /autoindex {
            autoindex on;
            root docs;
        }

        location /cgi-bin/ {
            root ./;
            cgi_extension .py;
            cgi_path /usr/bin/python3;
            allow_methods GET POST HEAD;
        }
    }

    server {
        listen 9090;
        location / {
            root docs/html;
            index index.html;
        }
    }
}
