#!/bin/bash

red='\033[0;31m'
green='\033[0;32m'
endcolor='\033[0m'

files=$(git diff --staged --name-only --diff-filter=ACM -- "*.h" "*.cpp")
if [ -z "$files" ]; then
    echo -e "${green} pre-commit 完了${endcolor}"
    exit 0
fi

echo "$files"
# format
echo "$files" | xargs clang-format -i

# lint
cpps=$(echo "$files" | grep -E "\.cpp$")
if [ -z "$cpps" ]; then
    echo -e "${green} pre-commit 完了${endcolor}"
    exit 0
fi

status=0
# for linux
# echo "$cpps" | xargs -I {} clang-tidy {} -- -I./src -std=c++98

# for mac
# echo "$cpps" | xargs -I {} clang-tidy {} -- -isysroot "$(xcrun --show-sdk-path)" -I./src -std=c++98
status=$?


if [ "$status" -gt 0 ]; then
    echo -e "${red} pre-commit 失敗${endcolor}"
    exit 1
fi

echo "$files" | xargs git add
echo -e "${green} pre-commit 完了${endcolor}"
