#!/bin/bash

red='\033[0;31m'
green='\033[0;32m'
endcolor='\033[0m'

files=$(git diff --staged --name-only --diff-filter=ACM -- "*.h" "*.cpp")
status=0
echo "$files"

if [ -n "$files" ]; then
    echo "$files" | xargs clang-format -i
    cpps=$(echo "$files" | grep -E "\.cpp$")
    if [ -n "$cpps" ]; then
        echo "$cpps" | xargs -I {} clang-tidy {} -- -I./src -std=c++98
        status=$?
    fi
fi



if [ "$status" -gt 0 ]; then
    echo -e "${red} pre-commit 失敗${endcolor}"
    exit 1
fi

echo "$files" | xargs git add
echo -e "${green} pre-commit 完了${endcolor}"
