name: C++ Linter & Formatter

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  lint-and-format:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v4

      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y clang-format clang-tidy

      # Run the Formatter (clang-format)
      - name: Run clang-format check
        run: |
          echo "Checking C++ formatting..."
          # Find all .cpp and .h files, but exclude any 'vendor' or 'lib' folders
          find . -type f \( -name "*.cpp" -o -name "*.h" \) -print0 | xargs -r -0 clang-format --dry-run --Werror -style=file
          echo "Formatting check passed!"

      # Run the Linter (clang-tidy)
      - name: Run clang-tidy
        run: |
          echo "Running C++ linter..."
          # Pass --warnings-as-errors='*' to fail the action on any issue
          find . -type f -name "*.cpp" -print0 | xargs -r -0 -I {} clang-tidy --warnings-as-errors='*' {} -- -std=c++98
          echo "Linter check passed!"
